#PROJECT_NAME := my_cool_project_name

# Build all files inside the following directories list:
VPATH := .

#C_SRC_FILESLIST := folder1/single_file_to_build.c folder2/another_single_file_to_build.c

-include Makefiles/Makefile_w_deps.mk
